import Head from "next/head";
import LandingPage from "./LandingPage";

export default function Home() {
  return <>
      <Head>
        <title>Divenco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
      </Head>
      <LandingPage />
  </>;
}
